[package]
name = "msg-stored"
version = "0.1.0"
authors = ["joshua enokson <kilograhm@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.10.0"
actix-web = "3"
actix-web-actors = "3"
bincode = "1.3.3"
clap = "2.33.3"
dirs = "1.0.4"
leveldb = "0.8"
msg-store = { path = "../msg-store" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
