openapi: 3.0.0
info:
  version: '0.1.0'
  title: 'msg-store'
servers:
  - url: 'localhost:8080'
paths:
  /api/export:
    get:
      summary: 'Exports messages to a file, while removing the messages from the store'
      parameters:
        - name: directory
          in: query
          description: "The directory to save the export file in"
          required: true
          schema:
            type: string
        - name: priority
          description: An optional priority group to export
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 4294967295
        - name: rangeStart
          description: A range of groups to export starting with this index
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 4294967295
        - name: rangeEnd
          description: A range of groups to export ending with this index
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 4294967295
      responses:
        '200':
          description: "Success response: Designated messages have been exported"
        '400':
          description: "Bad request: Missing or invalid parameter"
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: "Error response"

  /api/group:
    summary: "Perform priority group level operations"
    get:
      summary: 'Get group level metadata for one or more groups'
      parameters:
        - name: priority
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 4294967295
        - name: includeMsgData
          in: query
          required: false
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: "Success response: Returns metadata about groups"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    oneOf:
                      - $ref: '#/components/schemas/GroupGetOkOne'
                      - type: array
                        items:
                          $ref: "#/components/schemas/GroupGetOkOne"
        '400':
          description: 'Missing or invalid paramater'
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: 'Internal server error'
          content:
            text/plain:
              schema:
                type: string
    delete:
      summary: "Remove a group and it's messages from the store"
      parameters:
        - name: priority
          in: query
          required: true
          schema:
            type: integer
            minimum: 0
            maximum: 4294967295
      responses:
        '200':
          description: "Success response: The group and it's messaegs were removed"
        '400':
          description: "Bad request: Missing parameter"
          content:
              text/plain:
                schema:
                  type: string
        '500':
          description: "Internal server error"

  /api/group-defaults:
    post:
      description: "Insert or update a group's default configuration"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                priority:
                  type: integer
                  minimum: 0
                  maximum: 4294967295
                maxByteSize:
                  type: integer
                  minimum: 0
                  maximum: 4294967295
              required:
                - priority
                - maxByteSize
      responses:
        '200':
          description: "Success response: The default configuration was inserted/updated"
        '400':
          description: "Missing or invalid paramters"
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: 'Internal server error'
          content:
            text/plain:
              schema:
                type: string
    get:
      description: "Gets the default configuration of a priority group"
      parameters:
        - name: priority
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 4294967295
      responses:
        '200':
          description: "Success response: The group defaults are returned"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/GroupDefaultsGetOkOne"
                  - type: array
                    items:
                      $ref: "#/components/schemas/GroupDefaultsGetOkOne"
        '400':
          description: "Missing or invalid parameters"
          content:
              text/plain:
                schema:
                  type: string
                   
    delete:
      description: "Remove default configuration for a priority group"
      parameters:
        - name: priority
          in: query
          required: true
          schema:
            type: integer
            minimum: 0
            maximum: 4294967295
      responses:
        '200':
          description: "Success response: The default configuration was removed"
        '400':
          description: "Missing or invalid parameters"
          content:
              text/plain:
                schema:
                  type: string
        '500':
          description: "Internal server error: The default config was not removed"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    minimum: 1
                    maximum: 3
                  message:
                    type: string
                required:
                  - code
                  - message
    
  /api/msg:
    post:
      description: "Add a message the store"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                priority:
                  type: integer
                  minimum: 0
                  maximum: 4294967295
                msg:
                  type: string
              required:
                - priority
                - msg
      responses:
        '200':
          description: 'Success response: The message was added to the store'
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                required:
                  - uuid
        '400':
          description: 'Missing or invalid parameters'
        '409':
          description: 'No error was encountered, but the store rejected the message'
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
                    minimum: 0
                    maximum: 3
                  message:
                    type: string
                required:
                  - code
                  - message
        '500':
          description: 'Internal server error'
          content:
            text/plain:
              schema:
                type: string
    get:
      description: 'Get a message from the store'
      parameters:
        - name: uuid
          in: query
          required: false
          schema:
            type: string
        - name: priority
          in: query
          required: false
          schema:
            type: integer
            minimum: 0
            maximum: 4294967295
        - name: reverse
          in: query
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: 'Success response: A message was returned if found'
          content:
            appplication/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      uuid: 
                        type: string
                      msg:
                        type: string
        '400':
          description: 'Invalid parameter(s)'
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: 'Internal server error'
          content:
            text/plain:
              schema:
                type: string
    delete:
      description: "Removes a message from the store"
      parameters:
        - name: uuid
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Success response: The message was removed if present'
        '400':
          description: 'Missing or invalid uuid'
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: 'Internal server error'
          content:
            text/plain:
              schema:
                type: string
  
  /api/stats:
    get:
      description: "Get the store's inserted, deleted, and pruned count statistics"
      responses:
        '200':
          description: "Success response: The store's statistics are returned"
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      inserted:
                        type: integer
                        minimum: 0
                        maximum: 4294967295
                      deleted:
                        type: integer
                        minimum: 0
                        maximum: 4294967295
                      pruned:
                        type: integer
                        minimum: 0
                        maximum: 4294967295
        '500':
          description: "Internal server error"
          content:
            text/plain:
              schema:
                type: string
    put:
      description: "Update the store's statistics"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    replace:
                      type: object
                      properties:
                        inserted:
                          type: integer
                          minimum: 0
                          maximum: 4294967295
                        deleted:
                          type: integer
                          minimum: 0
                          maximum: 4294967295
                        pruned:
                          type: integer
                          minimum: 0
                          maximum: 4294967295
                - type: object
                  properties:
                    add:
                      type: object
                      properties:
                        inserted:
                          type: integer
                          minimum: 0
                          maximum: 4294967295
                        deleted:
                          type: integer
                          minimum: 0
                          maximum: 4294967295
                        pruned:
                          type: integer
                          minimum: 0
                          maximum: 4294967295
      responses:
        '200':
          description: "Success respons: The store's statistics were updated"
        '400':
          description: "Missing or invalid parameters"
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: 'Internal server error: The stats were not updated'
          content:
            text/plain:
              schema:
                type: string
    delete:
      description: "Reset the store's inserted, deleted, and pruned count statistics"
      responses:
        '200':
          description: "Success response: The store's statistics were reset"
          content:
            application/json:
              schema:
                type: object
                properties:
                  inserted:
                    type: integer
                    minimum: 0
                    maximum: 4294967295
                  deleted:
                    type: integer
                    minimum: 0
                    maximum: 4294967295
                  pruned:
                    type: integer
                    minimum: 0
                    maximum: 4294967295
                required:
                  - inserted
                  - deleted
                  - pruned
        '400':
          description: "Missing or invalid parameters"
          content:
              text/plain:
                schema:
                  type: string
        '500':
          description: 'Internal server error: The stats were not reset.'
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    GroupGetOkOne:
      type: object
      properties:
        priority:
          type: integer
          minimum: 0
          maximum: 4294967295
        byteSize:
          type: integer
          minimum: 0
          maximum: 4294967295
        maxByteSize:
          type: integer
          minimum: 0
          maximum: 4294967295
        msgCount:
          type:  integer
          minimum: 0
          maximum: 4294967295
        messages:
          type: array
          items:
            type: object
            properties:
              uuid:
                type: string
              byteSize:
                type: integer
                minimum: 0
                maximum: 4294967295
      required:
        - priority
        - byteSize
        - msgCount
        - messages
    GroupDefaultsGetOkOne:
      type: object
      properties:
        priority:
          type: integer
          minimum: 0
          maximum: 4294967295
        maxByteSize:
          type: integer
          minimum: 0
          maximum: 4294967295
      required:
        - priority
